# This is the BeamMP-Server config file.
# Help & Documentation: `https://wiki.beammp.com/en/home/server-maintenance`
# IMPORTANT: Fill in the AuthKey with the key you got from `https://beammp.com/k/dashboard` on the left under "Keys"

[General]
AuthKey = 'hujhujhujhujhujhujhuj'
Debug = false
Description = 'BeamMP Default Description'
Map = '/levels/west_coast_usa/info.json'
MaxCars = 1
MaxPlayers = 10
Name = 'ebat robit'
Port = 30814
Private = false
ResourceFolder = 'Resources'
